
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[206] =
    {   0,
       48,   48,   53,   53,    0,    0,    0,    0,   71,   69,
        2,    1,   21,   56,   28,   69,   68,   38,   39,   26,
       24,   44,   25,   69,   27,   47,   45,   29,   35,   31,
       46,   46,   42,   43,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   40,   69,   41,   52,
       51,   70,   62,   63,   61,   57,   58,   59,   70,    2,
       34,   36,   68,    0,    0,   68,   22,   23,   66,   48,
       50,   55,   67,   47,   67,   67,   48,   30,   33,   32,
       46,   46,    0,   46,   46,   46,   46,   46,   46,    7,
       46,   46,   46,    3,   46,   46,   46,   46,   46,   46,

       46,   37,   52,   53,   53,   54,   60,   68,   49,    0,
       68,   66,   66,    0,   65,   48,   55,   66,   48,   67,
       67,   48,   48,   46,   46,   46,   46,   46,   46,   46,
       46,    5,    9,   46,   46,   46,   46,   46,   46,    0,
       68,   64,    0,   49,   66,    0,   66,   65,   65,   48,
       65,   65,   66,   66,   67,   66,   65,   48,   46,   16,
       10,   46,   46,   46,    4,   46,   20,   46,   46,   46,
       13,   46,   53,   65,   65,   66,   66,   67,   66,   65,
       48,   65,    8,   46,   46,   46,   11,   46,   46,   46,
        6,   65,   65,   46,   46,   12,   46,   14,   15,   65,

       46,   17,   19,   18,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   40,   41,
       42,   43,   24,   44,   45,   46,   47,   48,   49,   24,
       24,   24,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    4,    1,    5,    5,    1,
        1,    1,    1,    5,    5,    1,    1,    1,    6,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1
    } ;

static yyconst flex_uint16_t yy_base[222] =
    {   0,
        0,    0,   50,   51,   52,   53,   57,   61,  199,  644,
       64,  644,  175,  644,  644,  182,   58,  644,  644,  644,
      168,  644,  162,   53,   58,   58,  644,  137,  100,   96,
       63,   71,  644,  644,   69,   75,   78,   80,   82,   88,
       84,   90,   97,  107,  109,  114,  644,   59,  644,    0,
      644,  118,  644,  644,  644,  111,  644,  644,  644,  135,
      644,  644,  127,   95,   86,  152,  644,  644,  130,  144,
      644,    0,  125,  155,  135,  173,  147,  644,  644,  644,
        0,  149,  157,  166,  176,  183,  185,  188,  190,  193,
      198,  195,  200,  202,  204,  208,  212,  214,  216,  220,

      228,  644,    0,   79,  128,  644,  644,  232,  644,   64,
      239,  245,  250,  258,  267,  274,    0,  278,  282,  236,
        0,  286,  290,  292,  295,  299,  301,  305,  307,  312,
      309,  314,  318,  322,  326,  330,  332,  335,  337,  239,
      258,  644,   48,  644,  341,  343,  346,  366,  373,  353,
      380,  384,  355,  388,  396,    0,  405,  412,  398,  414,
      416,  419,  421,  423,  425,  427,  429,  431,  434,  439,
      436,  441,  393,  445,  451,  447,  461,  468,  466,  475,
      479,  483,  485,  487,  490,  492,  494,  496,  498,  500,
      502,  504,  514,  506,  519,  522,  525,  527,  529,  531,

      533,  536,  538,  540,  644,  567,  573,  579,  585,  588,
      589,  595,  601,  607,  613,  619,  622,  623,  629,  635,
      638
    } ;

static yyconst flex_int16_t yy_def[222] =
    {   0,
      205,    1,  206,  206,  207,  207,  208,  208,  205,  205,
      205,  205,  205,  205,  205,  205,  209,  205,  205,  205,
      205,  205,  205,  205,  205,  210,  205,  205,  205,  205,
      211,  211,  205,  205,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  205,  205,  205,  212,
      205,  213,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  214,  205,  215,  214,  205,  205,  205,  205,
      205,  216,  217,  210,  217,  217,  217,  205,  205,  205,
      218,  211,  205,  218,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,

      211,  205,  212,  205,  213,  205,  205,  219,  205,  220,
      219,  205,  205,  205,  205,  205,  216,  217,  221,  217,
      221,  221,  205,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  213,
      219,  205,  220,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  118,  221,  217,  154,  221,  221,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  213,  205,  205,  154,  154,  221,  221,  221,
      221,  221,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  205,  221,  211,  211,  211,  211,  211,  211,  221,

      211,  211,  211,  211,    0,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205
    } ;

static yyconst flex_uint16_t yy_nxt[697] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   26,   27,
       28,   29,   30,   31,   32,   33,   10,   34,   31,   31,
       35,   36,   37,   38,   39,   31,   40,   31,   31,   41,
       31,   31,   42,   43,   44,   31,   31,   45,   46,   47,
       48,   49,   51,   51,   54,   54,  142,   55,   55,   58,
       59,   52,   52,   58,   59,   60,   64,   60,   69,   71,
       70,   70,  142,   73,   72,   74,   74,   65,   56,   56,
       81,   81,   76,   83,   66,   83,   81,   81,   84,   84,
      140,   77,   81,   81,  109,   81,   81,   81,   81,   81,

       81,   81,   81,  109,   86,   81,   81,   81,   81,  102,
       87,   89,   85,   96,   81,   81,   88,   80,   91,   90,
       92,   79,   94,   93,   81,   81,   81,   81,   95,  105,
       98,   81,   81,   97,  106,  109,   60,  107,   60,  105,
      118,  107,  119,  119,  106,  112,  110,  113,  113,  101,
      100,  107,  121,  121,  114,   99,  107,  111,   78,   69,
      109,   70,   70,  114,  121,  121,   81,   81,  115,  111,
       73,  110,   74,   74,  123,  123,   68,  116,  111,   76,
       67,  111,  111,   84,   84,   83,  111,   83,   77,   62,
      122,  122,  111,   81,   81,  111,   61,  111,  205,  111,

       81,   81,   81,   81,  205,   81,   81,   81,   81,  124,
       81,   81,   81,   81,  126,   81,   81,   81,   81,   81,
       81,   81,   81,  205,  128,   81,   81,  125,  127,   81,
       81,   81,   81,   81,   81,  205,  131,   81,   81,  129,
      142,  205,  130,  132,  134,   81,   81,  144,  135,  133,
      173,  143,  137,  121,  121,  205,  138,  205,  143,  136,
      112,  205,  145,  145,  139,  112,  142,  113,  113,  114,
      146,  205,  146,  205,  114,  147,  147,  143,  114,  148,
      205,  148,  149,  114,  150,  150,  151,  205,  151,  149,
      205,  152,  152,  153,  205,  154,  154,  156,  205,  119,

      119,  205,  155,  122,  122,  205,  157,  123,  123,   81,
       81,  155,   81,   81,  205,  158,   81,   81,   81,   81,
      205,  159,   81,   81,   81,   81,   81,   81,  160,   81,
       81,   81,   81,  205,  163,   81,   81,  164,  166,   81,
       81,  205,  161,   81,   81,  165,  162,   81,   81,   81,
       81,  205,   81,   81,   81,   81,  112,  205,  145,  145,
      147,  147,  167,  147,  147,  114,  168,  171,  175,  205,
      150,  150,  176,  176,  114,  172,  169,  170,  151,  205,
      151,  174,  205,  150,  150,  151,  205,  151,  149,  205,
      152,  152,  151,  205,  151,  174,  205,  152,  152,  175,

      205,  152,  152,  177,  173,  154,  154,  205,  146,  205,
      146,  205,  178,  179,  179,   81,   81,  148,  205,  148,
      180,  178,  181,  181,  151,  205,  151,  180,  205,  182,
      182,   81,   81,   81,   81,  183,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
      205,   81,   81,   81,   81,  184,   81,   81,   81,   81,
      174,  186,  152,  152,  176,  176,  175,  185,  192,  192,
      190,  205,  187,  205,  191,  205,  188,  189,  176,  176,
      146,  205,  146,  179,  179,  179,  179,  151,  205,  151,
      180,  205,  182,  182,  193,  205,  181,  181,  193,  205,

      182,  182,   81,   81,   81,   81,  205,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,  192,  192,   81,   81,  196,  205,  194,  195,  193,
      205,  200,  200,  205,  197,  199,   81,   81,  198,   81,
       81,  205,   81,   81,   81,   81,   81,   81,  200,  200,
       81,   81,  201,   81,   81,   81,   81,   81,   81,  205,
      205,  205,  205,  205,  202,  203,  204,   50,   50,   50,
       50,   50,   50,   53,   53,   53,   53,   53,   53,   57,
       57,   57,   57,   57,   57,   63,  205,   63,   63,   63,
       63,   75,   75,   82,   82,  103,  205,  205,  103,  103,

      103,  104,  205,  104,  104,  104,  104,  108,  205,  108,
      108,  108,  108,  110,  205,  110,  110,  110,  110,  117,
      205,  117,  117,  117,  117,  120,  120,   81,   81,  141,
      205,  141,  141,  141,  141,  143,  205,  143,  143,  143,
      143,  121,  121,    9,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205

    } ;

static yyconst flex_int16_t yy_chk[697] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,  143,    5,    6,    7,
        7,    3,    4,    8,    8,   11,   17,   11,   24,   25,
       24,   24,  110,   26,   25,   26,   26,   17,    5,    6,
       31,   31,   26,   32,   17,   32,   35,   35,   32,   32,
      104,   26,   36,   36,   65,   37,   37,   38,   38,   39,

       39,   41,   41,   64,   36,   40,   40,   42,   42,   48,
       36,   37,   35,   41,   43,   43,   36,   30,   38,   37,
       39,   29,   40,   39,   44,   44,   45,   45,   40,   52,
       43,   46,   46,   42,   52,   63,   60,   56,   60,  105,
       73,   56,   73,   73,  105,   69,   63,   69,   69,   46,
       45,   56,   75,   75,   69,   44,   56,   66,   28,   70,
       66,   70,   70,   69,   77,   77,   82,   82,   70,   66,
       74,   66,   74,   74,   83,   83,   23,   70,   66,   74,
       21,   66,   66,   84,   84,   76,   66,   76,   74,   16,
       76,   76,   66,   85,   85,   66,   13,   66,    9,   66,

       86,   86,   87,   87,    0,   88,   88,   89,   89,   85,
       90,   90,   92,   92,   87,   91,   91,   93,   93,   94,
       94,   95,   95,    0,   89,   96,   96,   86,   88,   97,
       97,   98,   98,   99,   99,    0,   92,  100,  100,   90,
      108,    0,   91,   93,   96,  101,  101,  111,   97,   95,
      140,  108,   99,  120,  120,  140,  100,    0,  111,   98,
      112,    0,  112,  112,  101,  113,  141,  113,  113,  112,
      114,    0,  114,    0,  113,  114,  114,  141,  112,  115,
        0,  115,  115,  113,  115,  115,  116,    0,  116,  116,
        0,  116,  116,  118,    0,  118,  118,  119,    0,  119,

      119,    0,  118,  122,  122,    0,  119,  123,  123,  124,
      124,  118,  125,  125,    0,  119,  126,  126,  127,  127,
        0,  124,  128,  128,  129,  129,  131,  131,  125,  130,
      130,  132,  132,    0,  128,  133,  133,  129,  131,  134,
      134,    0,  126,  135,  135,  130,  127,  136,  136,  137,
      137,    0,  138,  138,  139,  139,  145,    0,  145,  145,
      146,  146,  134,  147,  147,  145,  135,  138,  150,    0,
      150,  150,  153,  153,  145,  139,  136,  137,  148,    0,
      148,  148,    0,  148,  148,  149,    0,  149,  149,    0,
      149,  149,  151,    0,  151,  151,    0,  151,  151,  152,

        0,  152,  152,  154,  173,  154,  154,    0,  155,  173,
      155,    0,  154,  155,  155,  159,  159,  157,    0,  157,
      157,  154,  157,  157,  158,    0,  158,  158,    0,  158,
      158,  160,  160,  161,  161,  159,  162,  162,  163,  163,
      164,  164,  165,  165,  166,  166,  167,  167,  168,  168,
        0,  169,  169,  171,  171,  162,  170,  170,  172,  172,
      174,  164,  174,  174,  176,  176,  175,  163,  175,  175,
      170,    0,  166,    0,  172,    0,  168,  169,  177,  177,
      178,    0,  178,  179,  179,  178,  178,  180,    0,  180,
      180,    0,  180,  180,  181,    0,  181,  181,  182,    0,

      182,  182,  183,  183,  184,  184,    0,  185,  185,  186,
      186,  187,  187,  188,  188,  189,  189,  190,  190,  191,
      191,  192,  192,  194,  194,  186,    0,  184,  185,  193,
        0,  193,  193,    0,  188,  190,  195,  195,  189,  196,
      196,    0,  197,  197,  198,  198,  199,  199,  200,  200,
      201,  201,  194,  202,  202,  203,  203,  204,  204,    0,
        0,    0,    0,    0,  195,  197,  201,  206,  206,  206,
      206,  206,  206,  207,  207,  207,  207,  207,  207,  208,
      208,  208,  208,  208,  208,  209,    0,  209,  209,  209,
      209,  210,  210,  211,  211,  212,    0,    0,  212,  212,

      212,  213,    0,  213,  213,  213,  213,  214,    0,  214,
      214,  214,  214,  215,    0,  215,  215,  215,  215,  216,
        0,  216,  216,  216,  216,  217,  217,  218,  218,  219,
        0,  219,  219,  219,  219,  220,    0,  220,  220,  220,
      220,  221,  221,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1305043.l"



#line 6 "1305043.l"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
using namespace std;
#include"1305043_symbolTable.cpp"

# include "y.tab.h"
void yyerror(char*);


extern YYSTYPE yylval;
extern SymbolTable *myTable;
extern FILE* logFile;



extern int line_count;
extern int error_count;

string buff;
int myCount;
bool checkInsert;

#line 719 "lex.yy.c"

#define INITIAL 0
#define mlcomment 1
#define mlstring 2
#define helpState 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 60 "1305043.l"



#line 944 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 206 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 644 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 63 "1305043.l"
{line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "1305043.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 68 "1305043.l"
{
			
			//fprintf(tokenFile,"<IF>");
			fprintf(logFile,"Line no %03d: TOKEN <IF> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return IF; 
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <ELSE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return ELSE;
/*			fprintf(tokenFile,"<ELSE>");
			fprintf(logFile,"Line no %03d: TOKEN <ELSE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");*/
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <FOR> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return FOR;
		/*	fprintf(tokenFile,"<FOR>");
			fprintf(logFile,"Line no %03d: TOKEN <FOR> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "1305043.l"
{	fprintf(logFile,"Line no %03d: TOKEN <WHILE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return WHILE;
			/*fprintf(tokenFile,"<WHILE>");
			fprintf(logFile,"Line no %03d: TOKEN <WHILE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "1305043.l"
{	
			fprintf(logFile,"Line no %03d: TOKEN <DO> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return DO;
			/*fprintf(tokenFile,"<DO>");
			fprintf(logFile,"Line no %03d: TOKEN <DO> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");*/
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 107 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <BREAK> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return BREAK;
			/*fprintf(tokenFile,"<BREAK>");
			fprintf(logFile,"Line no %03d: TOKEN <BREAK> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 115 "1305043.l"
{
			
		/*	fprintf(tokenFile,"<INT>");*/
			fprintf(logFile,"Line no %03d: TOKEN <INT> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return INT;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <CHAR> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return CHAR;
		/*
			fprintf(tokenFile,"<CHAR>");
			fprintf(logFile,"Line no %03d: TOKEN <CHAR> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 131 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <FLOAT> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return FLOAT;
/*			fprintf(tokenFile,"<FLOAT>");
			fprintf(logFile,"Line no %03d: TOKEN <FLOAT> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");*/
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 139 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <DOUBLE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return DOUBLE;
			/*
			fprintf(tokenFile,"<DOUBLE>");
			fprintf(logFile,"Line no %03d: TOKEN <DOUBLE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 148 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <VOID> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return VOID;
			/*
			fprintf(tokenFile,"<VOID>");
			fprintf(logFile,"Line no %03d: TOKEN <VOID> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 157 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <RETURN> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return RETURN;
			/*
			fprintf(tokenFile,"<RETURN>");
			fprintf(logFile,"Line no %03d: TOKEN <RETURN> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 166 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <SWITCH> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return SWITCH;
			/*
			fprintf(tokenFile,"<SWITCH>");
			fprintf(logFile,"Line no %03d: TOKEN <SWITCH> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 175 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <CASE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return CASE;
			/*
			fprintf(tokenFile,"<CASE>");
			fprintf(logFile,"Line no %03d: TOKEN <CASE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 184 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <DEFAULT> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return DEFAULT;
			/*
			fprintf(tokenFile,"<DEFAULT>");
			fprintf(logFile,"Line no %03d: TOKEN <DEFAULT> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 193 "1305043.l"
{
			fprintf(logFile,"Line no %03d: TOKEN <CONTINUE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
			return CONTINUE;
			/*
			fprintf(tokenFile,"<CONTINUE>");
			fprintf(logFile,"Line no %03d: TOKEN <CONTINUE> Lexeme <%s> found\n",line_count,yytext);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 203 "1305043.l"
{

			return PRINTLN;
			
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 209 "1305043.l"
{
			return MAIN;
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 213 "1305043.l"
{
				buff="";buff+=yytext;
				SymbolInfo* info=new SymbolInfo(buff,"NOT");
				yylval=(YYSTYPE)info;
				
				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <NOT> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : NOT> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return NOT;
		}
	YY_BREAK
case 22:
#line 230 "1305043.l"
case 23:
YY_RULE_SETUP
#line 231 "1305043.l"
{
			buff="";buff+=yytext;
			if(buff=="++"){
				SymbolInfo* info=new SymbolInfo(buff,"INCOP");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <INCOP> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : INCOP> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");
				
				return INCOP;
			}
			else{
			 	SymbolInfo* info=new SymbolInfo(buff,"DECOP");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <DECOP> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : DECOP> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");


			 	return DECOP;
			 }
			


	/*
			fprintf(tokenFile,"<INCOP,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <INCOP> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("INCOP");
			myInfo.setName(yytext);
			fprintf(logFile,"\n\n");
*/		}
	YY_BREAK
case 24:
#line 274 "1305043.l"
case 25:
YY_RULE_SETUP
#line 275 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo *info=new SymbolInfo(buff,"ADDOP");
			yylval=(YYSTYPE)info;

			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <ADDOP> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : ADDOP> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");



			return ADDOP;

		/*	fprintf(tokenFile,"<ADDOP,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <ADDOP> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("ADDOP");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : ADDOP> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 26:
#line 301 "1305043.l"
case 27:
#line 302 "1305043.l"
case 28:
YY_RULE_SETUP
#line 302 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo *info=new SymbolInfo(buff,"MULOP");
			yylval=(YYSTYPE)info;

			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <MULOP> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : MULOP> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");

			return MULOP;
			/*fprintf(tokenFile,"<MULOP,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <MULOP> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("MULOP");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : MULOP> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 29:
#line 326 "1305043.l"
case 30:
#line 327 "1305043.l"
case 31:
#line 328 "1305043.l"
case 32:
#line 329 "1305043.l"
case 33:
#line 330 "1305043.l"
case 34:
YY_RULE_SETUP
#line 330 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo* info=new SymbolInfo(buff,"RELOP");
			yylval=(YYSTYPE)info;
			
			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <RELOP> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : RELOP> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
			
			return RELOP;
		/*	fprintf(tokenFile,"<RELOP,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <RELOP> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("RELOP");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : RELOP> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
*/
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 354 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo* info=new SymbolInfo(buff,"ASSIGNOP");
			yylval=(YYSTYPE)info;

			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <ASSIGNOP> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : ASSIGNOP> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");

			return ASSIGNOP;
			/*fprintf(tokenFile,"<ASSIGNOP,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <ASSIGNOP> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("ASSIGNOP");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : ASSIGNOP> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");*/
		}
	YY_BREAK
case 36:
#line 378 "1305043.l"
case 37:
YY_RULE_SETUP
#line 378 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo *info=new SymbolInfo(buff,"LOGICOP");
			yylval=(YYSTYPE)info;

			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <LOGICOP> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : LOGICOP> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");

			return LOGICOP;
		/*	fprintf(tokenFile,"<LOGICOP,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <LOGICOP> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("LOGICOP");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : LOGICOP> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 38:
#line 402 "1305043.l"
case 39:
YY_RULE_SETUP
#line 402 "1305043.l"
{
			buff="";buff+=yytext;
			if(buff=="("){
				SymbolInfo *info=new SymbolInfo(buff,"LPAREN");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <LPAREN> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : LPAREN> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return LPAREN;
			}
			else{
				SymbolInfo *info=new SymbolInfo(buff,"RPAREN");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <RPAREN> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : RPAREN> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return RPAREN;	
			} 
		}
	YY_BREAK
case 40:
#line 433 "1305043.l"
case 41:
YY_RULE_SETUP
#line 433 "1305043.l"
{
			buff="";buff+=yytext;
			if(buff=="{"){
				SymbolInfo* info=new SymbolInfo(buff,"LCURL");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <LCURL> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : LCURL> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return LCURL;
			}
			else{
				SymbolInfo* info=new SymbolInfo(buff,"RCURL");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <RCURL> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : RCURL> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return RCURL;
			}

			/*
			fprintf(tokenFile,"<%s,%s>",buff.c_str(),yytext);
			fprintf(logFile,"Line no %03d: TOKEN <%s> Lexeme <%s> found\n",line_count,buff.c_str(),yytext);
			myInfo.setType(buff);
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : %s> already exists\n",yytext,buff.c_str());
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 42:
#line 474 "1305043.l"
case 43:
YY_RULE_SETUP
#line 474 "1305043.l"
{
			buff="";buff+=yytext;
			if(buff=="["){
				SymbolInfo* info=new SymbolInfo(buff,"LTHIRD");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <LTHIRD> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : LTHIRD> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return LTHIRD;
			}
			else{
				SymbolInfo* info=new SymbolInfo(buff,"RTHIRD");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <RTHIRD> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : RTHIRD> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return RTHIRD;
			}
			/*
			fprintf(tokenFile,"<%s,%s>",buff.c_str(),yytext);
			fprintf(logFile,"Line no %03d: TOKEN <%s> Lexeme <%s> found\n",line_count,buff.c_str(),yytext);
			myInfo.setType(buff);
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : %s> already exists\n",yytext,buff.c_str());
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 514 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo* info=new SymbolInfo(buff,"COMMA");
			yylval=(YYSTYPE)info;

			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <COMMA> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : COMMA> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");

			return COMMA;
			/*
			fprintf(tokenFile,"<COMMA,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <COMMA> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("COMMA");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : COMMA> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 538 "1305043.l"
{
			buff="";buff+=yytext;
			SymbolInfo* info=new SymbolInfo(buff,"SEMICOLON");
			yylval=(YYSTYPE)info;

			checkInsert=myTable->Insert(*info);
			fprintf(logFile,"Line no %03d: TOKEN <SEMICOLON> Lexeme <%s> found\n",line_count,yytext);
			if(!checkInsert)fprintf(logFile,"<%s : SEMICOLON> already exists\n",yytext);
			fprintf(logFile,"\n\n");
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");

			return SEMICOLON;
			/*
			fprintf(tokenFile,"<SEMICOLON,%s>",yytext);
			fprintf(logFile,"Line no %03d: TOKEN <SEMICOLON> Lexeme <%s> found\n",line_count,yytext);
			myInfo.setType("SEMICOLON");
			myInfo.setName(yytext);
			checkInsert=myTable->Insert(myInfo);
			if(!checkInsert)fprintf(logFile,"<%s : SEMICOLON> already exists\n",yytext);
			myTable->Print(logFile);
			fprintf(logFile,"\n\n");
		*/}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 562 "1305043.l"
{
				buff="";buff+=yytext;
				SymbolInfo* info=new SymbolInfo(buff,"ID");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <ID> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : ID> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return ID;
			/*	fprintf(tokenFile,"<ID,%s>",yytext);
				fprintf(logFile,"Line no %03d: TOKEN <ID> Lexeme <%s> found\n",line_count,yytext);
				myInfo.setType("ID");
				myInfo.setName(yytext);
				checkInsert=myTable->Insert(myInfo);
				if(!checkInsert)fprintf(logFile,"<%s : ID> already exists\n",yytext);
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");
			*/}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 587 "1305043.l"
{
				buff="";buff+=yytext;
				SymbolInfo*info=new SymbolInfo(buff,"CONST_INT");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <CONST_INT> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : CONST_INT> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return CONST_INT;
	/*
				fprintf(tokenFile,"<CONST_INT,%s>",yytext);
				fprintf(logFile,"Line no %03d: TOKEN <CONST_INT> Lexeme <%s> found\n",line_count,yytext);
				myInfo.setType("CONST_INT");
				myInfo.setName(yytext);
				checkInsert=myTable->Insert(myInfo);
				if(!checkInsert)fprintf(logFile,"<%s : CONST_INT> already exists\n",yytext);
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");
	*/		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 611 "1305043.l"
{

				buff="";buff+=yytext;
				SymbolInfo* info=new SymbolInfo(buff,"CONST_FLOAT");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <CONST_FLOAT> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : CONST_FLOAT> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return CONST_FLOAT;
	/*
				fprintf(tokenFile,"<CONST_FLOAT,%s>",yytext);
				fprintf(logFile,"Line no %03d: TOKEN <CONST_FLOAT> Lexeme <%s> found\n",line_count,yytext);
				myInfo.setType("CONST_FLOAT");
				myInfo.setName(yytext);
				checkInsert=myTable->Insert(myInfo);
				if(!checkInsert)fprintf(logFile,"<%s : CONST_FLOAT> already exists\n",yytext);
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");
	*/		}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 636 "1305043.l"
{
				buff="";buff+=yytext;
				SymbolInfo *info=new SymbolInfo(buff,"CONST_CHAR");
				yylval=(YYSTYPE)info;

				checkInsert=myTable->Insert(*info);
				fprintf(logFile,"Line no %03d: TOKEN <CONST_CHAR> Lexeme <%s> found\n",line_count,yytext);
				if(!checkInsert)fprintf(logFile,"<%s : CONST_CHAR> already exists\n",yytext);
				fprintf(logFile,"\n\n");
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");

				return CONST_CHAR;

	/*
				fprintf(tokenFile,"<CONST_CHAR,%s>",yytext);
				fprintf(logFile,"Line no %03d: TOKEN <CONST_CHAR> Lexeme <%s> found\n",line_count,yytext);
				myInfo.setType("CONST_CHAR");
				myInfo.setName(yytext);
				checkInsert=myTable->Insert(myInfo);
				if(!checkInsert)fprintf(logFile,"<%s : CONST_CHAR> already exists\n",yytext);
				myTable->Print(logFile);
				fprintf(logFile,"\n\n");
	*/		}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 663 "1305043.l"
{

				myCount=line_count;
				buff="";
				buff+=yytext;		
				BEGIN(mlcomment);
					
			}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 671 "1305043.l"
{
					line_count++;
					buff+=yytext;
				} 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 675 "1305043.l"
{
					buff+=yytext;

					}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 679 "1305043.l"
{
					buff+=yytext;

				}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 683 "1305043.l"
{
					buff+=yytext;
					fprintf(logFile,"Line no %03d: TOKEN <COMMENT> Lexeme <%s> found\n",myCount,buff.c_str());
					fprintf(logFile,"\n\n");	
					BEGIN(INITIAL);
				}
	YY_BREAK
case YY_STATE_EOF(mlcomment):
#line 689 "1305043.l"
{
				fprintf(logFile,"Line no %03d: ERROR!! - Undeterminated comment %s\n",myCount,buff.c_str());
				fprintf(logFile,"\n\n");
				error_count++;
				BEGIN(INITIAL);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 697 "1305043.l"
{
				buff="";
				char *ch=yytext;
				while(*ch){
					if(*ch=='\r'){
						*ch++;
						continue;
					}
					buff+=*ch++;
				}
				fprintf(logFile,"Line no %03d: TOKEN <COMMENT> Lexeme <%s> found\n",line_count,buff.c_str());
				fprintf(logFile,"\n\n");
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 713 "1305043.l"
{
				myCount=line_count;
				buff="";
				buff+=yytext;
				BEGIN(mlstring);
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 720 "1305043.l"
{
	//fprintf(logFile,"Line no. %d: backslash found\n",line_count);
	BEGIN(helpState);

}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 725 "1305043.l"
{
	//fprintf(logFile,"Line no. %d: begin from helpState 1\n",line_count);
	buff+=yytext;
	BEGIN(mlstring);
}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 731 "1305043.l"
{
		//fprintf(logFile,"Line no. %d: begin from helpState 2\n",line_count);
		line_count++;
		BEGIN(mlstring);
	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 737 "1305043.l"
{
		char *ch=yytext;
		ch++;
		while(*ch){
			if(*ch=='\n'||*ch=='\r'){
				*ch++;continue;
			}
			else if(*ch=='\\'){
				buff+='\\';*ch++;
			}
			else if(*ch=='n'){
				buff+='\n';*ch++;
			}
			else if(*ch=='t'){
				buff+='\t';*ch++;
			}
			else if(*ch=='b'){
				buff+='\b';*ch++;
			}
			else buff+=*ch++;
		}
	}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 759 "1305043.l"
{
					buff+=yytext;
					BEGIN(INITIAL);

					SymbolInfo *info=new SymbolInfo(buff,"STRING");
					yylval=(YYSTYPE)info;

					fprintf(logFile,"Line no %03d: TOKEN <STRING> Lexeme <%s> found\n",line_count,yytext);
					fprintf(logFile,"\n\n");
					return STRING;
					// fprintf(tokenFile,"<STRING,%s>",buff.c_str());
					// fprintf(logFile,"Line no %03d: TOKEN <STRING> Lexeme",myCount);
					// fprintf(logFile," %s found\n",buff.c_str());
					// fprintf(tokenFile,"<STRING,%s>",buff.c_str());
					// fprintf(logFile,"\n\n");
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 775 "1305043.l"
{
		char *ch=yytext;
		while(*ch){
			if(*ch=='\n'||*ch=='\r'||*ch=='\\'){
				*ch++;continue;
			}
			buff+=*ch++;
		}
}
	YY_BREAK
case YY_STATE_EOF(mlstring):
#line 784 "1305043.l"
{
				char *ch=yytext;
				while(*ch){
						if(*ch=='\n'||*ch=='\r'||*ch=='\\'){
						*ch++;continue;
					}
					buff+=*ch++;
				}
				// fprintf(logFile,"Line no %03d: ERROR!! - Unfinished String %s\n",myCount,buff.c_str());
				// fprintf(logFile,"\n\n");
				error_count++;
				BEGIN(INITIAL);
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 799 "1305043.l"
{
				line_count++;
				char *ch=yytext;
				while(*ch){
						if(*ch=='\n'||*ch=='\r'||*ch=='\\'){
						*ch++;continue;
					}
					buff+=*ch++;
				}
				// fprintf(logFile,"Line no %03d: ERROR!! - Unfinished String %s\n",myCount,buff.c_str());
				// fprintf(logFile,"\n\n");
				error_count++;
				BEGIN(INITIAL);
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 815 "1305043.l"
{
				// fprintf(logFile,"Line no %03d: ERROR!! - Multi charachter constant %s\n",line_count,yytext);
				// fprintf(logFile,"\n\n");
				error_count++;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 823 "1305043.l"
{
				// fprintf(logFile,"Line no %03d: ERROR!! - Ill formed number %s\n",line_count,yytext);
				// fprintf(logFile,"\n\n");
				error_count++;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 830 "1305043.l"
{
				// fprintf(logFile,"Line no %03d: ERROR!! - Too many decimal points %s\n",line_count,yytext);
				// fprintf(logFile,"\n\n");
				error_count++;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 836 "1305043.l"
{
				// fprintf(logFile,"Line no %03d: ERROR!! - Invalid prefix %s\n",line_count,yytext);
				// fprintf(logFile,"\n\n");
				error_count++;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 843 "1305043.l"
{
				// fprintf(logFile,"Line no %03d: ERROR!! - Ill formed charachter error %s\n",line_count,yytext);
				// fprintf(logFile,"\n\n");
				error_count++;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 852 "1305043.l"
{
				// fprintf(logFile,"Line no %03d: ERROR!! - Unrecognized charachter found %s\n",line_count,yytext);
				// fprintf(logFile,"\n\n");
				error_count++;
				//insert in symbol table and print symbol table content(only non empty buckets)
			}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 862 "1305043.l"
ECHO;
	YY_BREAK
#line 2001 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(helpState):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 206 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 206 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 205);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 862 "1305043.l"



int yywrap(void)
{
	return 1;
}



/*int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("No input file provided\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("File can't be opened\n");
		return 0;
	}
	
	logFile= fopen("1305043_log.txt","w");
	tokenFile= fopen("1305043_token.txt","w");
	myTable=new SymbolTable(15);

	yyin=fin;
	yylex();

	fprintf(logFile,"\n\nTOTAL LINES: %03d\n",line_count);
	fprintf(logFile,"\n\nTOTAL ERRORS: %03d\n",error_count);

	fclose(yyin);
	fclose(tokenFile);
	fclose(logFile);
	return 0;
}*/
